started work on each executable, finished base command. switching computers

diff --git a/bin/git-v-down b/bin/git-v-down
--- a/bin/git-v-down
+++ b/bin/git-v-down
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
 #
-# push functionality of git-xfer plugin
+# increment version numbers for marked files
 # 
 # @author <bprinty@gmail.com>
 # ------------------------------------------------
@@ -9,67 +9,40 @@
 # meta
 # ----
 usage() {
-    echo "usage: git xfer add [options] <file>"
+    echo "usage: git v down [options] <type>"
+    echo ""
+    echo "Arguments:"
+    echo "  type               major, minor, or subminor (major.minor.subminor)"
     echo ""
     echo "Options:"
-    echo "  -h | --help              Show help and exit."
-    echo "  -n | --no-ignore         Do not update .gitignore with tracked files."
+    echo "  --help              Show help and exit."
 }
 
 
 # exec
 # ----
-add(){
-    if [ `uname` = "Darwin" ]; then
-        shasum=`shasum "$1" | awk '{ print $1 }'`
-    else
-        shasum=`sha1sum "$1" | awk '{ print $1 }'`
-    fi
-    fname=$(echo "$1" | sed "s|$base|.|" | sed 's/ /\\ /'g)
-    echo "$shasum  $fname" >> "$cache"
-    if [ "$gitignore" = "TRUE" ]; then
-        if [ ! `grep "$fname" "$base/.gitignore"` ]; then
-            echo "$fname" | sed "s|./||" >> "$base/.gitignore"
-            git add "$base/.gitignore"
-        fi
-    fi
-    sort "$cache" | uniq > "$cache.lck"
-    mv "$cache.lck" "$cache"    
-}
-
 main() {
     if [ "$#" -lt 1 ]; then
         usage; exit 1
     fi
 
-    gitignore='TRUE'
     case "$1" in
         "-h"|"--help")
             usage; exit 0
             ;;
-        "-n"|"--no-ignore")
-            gitignore='FALSE'; shift
-            ;;
     esac
 
-    touch "$cache"
-    OLDIFS=$IFS;
-    IFS="$(printf '\n\t')"
-    for i in "$@"; do
-        if [ "$i" = "." ]; then
-            fullpath="`pwd`"
-        else
-            fullpath=$(cd "$(dirname $i)" && pwd -P)/$(basename "$i")
+    for i in `cat $marks`; do
+        version=`grep -Eoh '\d\.\d\.\d(-rc[0-9a-f]{7})?' $i`
+        if [ "$version" = "" ]; then
+            echo "No version-like string found in $i. Abort!"
+            exit 1
         fi
-        if [ -d "$fullpath" ]; then
-            find "$fullpath" -type f -exec git xfer add {} \;
-        else
-            add "$fullpath"
-        fi
+        # STOPPED HERE .. NEED TO INCREMENT VERSION NUMBER
+        echo $i
     done
-    IFS=$OLDIFS
 }
 
 base=`git rev-parse --show-toplevel`
-cache="$base/.git/xfer/cache"
+marks="$base/.git/version/marks"
 main "$@"
diff --git a/bin/git-v-list b/bin/git-v-list
--- a/bin/git-v-list
+++ b/bin/git-v-list
@@ -9,11 +9,15 @@
 # meta
 # ----
 usage() {
-    echo "usage: git xfer list [options] [<remote>]"
+    echo "usage: git v list [--help]"
     echo ""
     echo "Options:"
     echo "  -h | --help              Show help and exit."
-    echo "  -f | --files             Show only files."
+}
+
+version() {
+    file="$1"
+    cat "$file" | grep ''
 }
 
 
@@ -21,32 +25,23 @@ usage() {
 # ----
 main() {
 
-    local FILES="FALSE"
-
     case $1 in
         "-h"|"--help")
             usage; exit 0
             ;;
-        "-f"|"--files")
-            FILES="TRUE"; shift
-            ;;
     esac
 
-    if [ ! -z $1 ]; then
-        cache="$cache-$1"
-    fi
-
     if [ ! -e "$cache" ]; then
-       echo ''; exit 0
+       echo 'Could not find tracking list! Something went wrong with your configuration.'
+       exit 1
     fi
 
-    if [ "$FILES" = "TRUE" ]; then
-        cat "$cache" | sed 's/.*\.\//.\//g' | sed 's/  local.*//g'
-    else
-        cat "$cache"
-    fi
+    for i in `cat $marks`; do
+        version=`grep -Eoh '\d\.\d\.\d(-rc[0-9a-f]{7})?' $i`
+        echo "$i ... $version"
+    done
 }
 
 base=`git rev-parse --show-toplevel`
-cache="$base/.git/xfer/cache"
+marks="$base/.git/version/marks"
 main "$@"
